name: AI LLM Code Review Workflow
on:
  push:
    branches:
      - '*'
jobs:
  openai-code-review:
    runs-on: ubuntu-latest
    name: OpenAI LLM Code Review
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
      - name: Filter Java Files
        id: changed-java-files
        uses: tj-actions/changed-files@v44
        with:
            # Avoid using single or double quotes for multiline patterns
            files: |
              **.java
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-java-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
              echo "$file was changed"
          done
        shell:
          bash
      - name: Open AI Review code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}
          CHATGPT_MODEL: "gpt-4o"
        run: |
      #        创建评审结果文件
              touch result_review.txt
              for file in ${{ steps.changed-java-files.outputs.all_changed_files }}; do
                  content=$(cat "$file")
                  airesponse=$(curl -X POST https://api.openai.com/v1/chat/completions 
                    -H "Content-Type:application/json" 
                    -H "Authorization:Bearer $CHATGPT_KEY" 
                    -d '{"model":"$CHATGPT_MODEL","messages":[
                    {"role":"system","content":"你是一个Java技术专家,请对我的代码进行评审，提出优化建议与问题."},
                    {"role":"user","content":"我给你提供的代码如下:$content"}]' | jq -r '.response')
                  echo "Response from OpenAI:"
                  echo "$airesponse"
                  comment="Code Review for \`$file\`:\n\n  $airesponse"
                   echo "$comment" >> result_review.txt
              done
        shell: bash

      - name: Commit review result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name 'aibot2024'
            git config --global user.email 'aibot2024@users.noreply.github.com'
            git add openai_review.txt
            git commit -m "Add OpenAI code review result"
            git push
        shell:
          bash